### ISSUE TITLE
AWS SDK hangs?

### ISSUE THREAD

**Issue by takus** [takus/fluent-plugin-dynamodb-streams#1]
```
  Thread #<Thread:0x007f0938753c10> status=sleep priority=0
      /opt/td-agent/embedded/lib/ruby/2.1.0/net/protocol.rb:155:in `select'
      /opt/td-agent/embedded/lib/ruby/2.1.0/net/protocol.rb:155:in `rescue in rbuf_fill'
      /opt/td-agent/embedded/lib/ruby/2.1.0/net/protocol.rb:152:in `rbuf_fill'
      /opt/td-agent/embedded/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
      /opt/td-agent/embedded/lib/ruby/2.1.0/net/protocol.rb:144:in `readline'
      /opt/td-agent/embedded/lib/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'
      /opt/td-agent/embedded/lib/ruby/2.1.0/net/http/response.rb:28:in `read_new'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/net_http/patches.rb:29:in `block in new_transport_request'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/net_http/patches.rb:26:in `catch'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/net_http/patches.rb:26:in `new_transport_request'
      /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:1378:in `request'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/net_http/connection_pool.rb:337:in `request'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/net_http/handler.rb:61:in `block in transmit'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/net_http/handler.rb:110:in `block in session'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/net_http/connection_pool.rb:108:in `session_for'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/net_http/handler.rb:108:in `session'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/net_http/handler.rb:60:in `transmit'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/net_http/handler.rb:34:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/plugins/content_length.rb:12:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/aws-sdk-core/json/error_handler.rb:8:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/aws-sdk-core/plugins/request_signer.rb:85:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/aws-sdk-core/plugins/retry_errors.rb:87:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/aws-sdk-core/json/handler.rb:11:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/plugins/endpoint.rb:34:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/aws-sdk-core/plugins/param_converter.rb:21:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/plugins/response_target.rb:21:in `call'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/request.rb:70:in `send_request'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.20/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-dynamodb-streams-0.0.1/lib/fluent/plugin/in_dynamodb_streams.rb:91:in `block in run'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-dynamodb-streams-0.0.1/lib/fluent/plugin/in_dynamodb_streams.rb:69:in `each'
      /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-dynamodb-streams-0.0.1/lib/fluent/plugin/in_dynamodb_streams.rb:69:in `run'
```

**Comment by takus** [comment]
resolved by #3
